version: "3"
services:

  react-ui:
    build:
      context: ./react-ui
      dockerfile: Docker
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./react-ui/src:/usr/app/src
      - ./react-ui/public:/usr/app/public
    depends_on:
      - node-server
    environment:
      - REACT_APP_SERVER=http://localhost:8181
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true

  node-server:
    build:
      context: ./node-server
      dockerfile: Docker
    ports:
      - 8181:8181
    depends_on:
      - mongodbc
    networks:
      - mern-network
    volumes:
      - ./node-server/src:/usr/app/src
    #environment:
    #  - MONGO_URL=mongodb://db:27017
    #  - CLIENT=http://localhost:3000
    command: npm start

  mongodbc:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongodb-vol:/data/db

volumes:
  mongodb-vol:
networks:
  mern-network:
    driver: bridge

#working both React and Express
#docker-compose build
#docker-compose up
#docker-compose up -d -build
#docker network create mern-network