apiVersion: v1
kind: Namespace
metadata:
  name: k8-mern-namespace

#   kubectl create -f ./my-namespace.yaml
#   kubectl create namespace k8-mern-namespace
#   https://kubernetes.io/docs/tasks/administer-cluster/namespaces/
# https://matthewpalmer.net/kubernetes-app-developer/articles/service-kubernetes-example-tutorial.html